#!/usr/bin/env python3
"""One-shot seed for the definition wiki. Do not re-run after answers; it overwrites Draft pages."""

from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
WIKI = ROOT / "wiki"
TERMS = WIKI / "terms"
SYSTEMS = WIKI / "systems"

# whose: "Yours" or "Sim name"
# systems: tags used to build system pages
# not_: optional neighbor confusion
# fight: optional doc disagreement

TERMS_DATA = [
    # People
    dict(slug="caveman", title="Caveman", whose="Yours", systems=["people"],
         definition="Any male NPC. In settled play he belongs to a clan that has a land claim.",
         not_="Not automatically a wild human. A male with no claim is a wild caveman, and that path is still a plan.",
         fight="The short table in bible.md still says “wild humans.” The dictionary and the exile doc replaced that line.",
         related=["clansman", "wild-caveman", "woman"]),
    dict(slug="clansman", title="Clansman", whose="Yours", systems=["people"],
         definition="A caveman who belongs to a clan. The word stresses membership and jobs (work, defend, follow, raid). Women and herd animals are not clansmen.",
         not_="Not a woman, and not a herd animal, even when those are part of the clan.",
         fight="gdd.md still says clansmen are only surplus babies turned into an army. The current dictionary meaning is any male in the clan.",
         related=["caveman", "baby", "worker", "part-of-the-clan"]),
    dict(slug="woman", title="Woman", whose="Yours", systems=["people", "huts"],
         definition="Female NPC. Not a clansman. She can be part of the clan once claimed or assigned. Same genetics layer as fighters.",
         not_="Not a clansman.",
         related=["herdable", "part-of-the-clan", "living-hut"]),
    dict(slug="baby", title="Baby", whose="Yours", systems=["people", "huts"],
         definition="Child before promotion. Grows with the mother, then a timer promotes him to a clansman (male) today. Not a clansman until then.",
         fight="Female babies (grow into women) are planned, not current.",
         related=["baby-pool", "clansman", "living-hut"]),
    dict(slug="baby-pool", title="Baby pool", whose="Yours", systems=["people", "huts"],
         definition="A cap on how many babies the clan can hold. Each Living Hut adds room. Extra babies become clansmen.",
         fight="bible.md also says population is driven by the hut itself (one woman and her children), not only an abstract pool. Both ideas are in the docs.",
         related=["baby", "living-hut"]),
    dict(slug="worker", title="Worker", whose="Yours", systems=["people"],
         definition="A clansman who is not on defend duty (gather, build, craft, follow orders).",
         not_="Not a defender.",
         related=["defender", "clansman", "searcher"]),
    dict(slug="defender", title="Defender", whose="Yours", systems=["people", "orders"],
         definition="A clansman assigned to guard the claim edge (flag border or campfire edge). Not anyone who is fighting.",
         not_="Not Guard. Guard is a moving party stance. A defender stays on the border.",
         related=["guard", "worker", "defender-quota", "land-claim"]),
    dict(slug="searcher", title="Searcher", whose="Yours", systems=["people", "orders"],
         definition="A clansman the clan sends into the wilderness to find herdables.",
         related=["herd", "searcher-quota", "wilderness", "herdable"]),
    dict(slug="herder", title="Herder", whose="Yours", systems=["people", "orders"],
         definition="Whoever is leading herdables: the player or a clansman. The animal or woman decides to attach. Cavemen do not own them.",
         related=["herd", "herdable", "herd-influence-area"]),
    dict(slug="herdable", title="Herdable", whose="Yours", systems=["people", "orders"],
         definition="Someone who can be herded: women, sheep, goats, and similar animals. Predators cannot.",
         not_="Not a predator, and not a clansman.",
         related=["herd", "woman", "predator", "claimed"]),
    dict(slug="wild-npc", title="Wild NPC", whose="Yours", systems=["people"],
         definition="An NPC without a clan. Includes herdables and enemies. Enemies cannot be herded.",
         related=["wild", "herdable", "predator"]),
    dict(slug="wild", title="Wild", whose="Yours", systems=["people", "exile"],
         definition="No clan owns that NPC.",
         not_="Not the same word as wilderness. Wilderness is land. Wild is the NPC.",
         related=["claimed", "wilderness", "wild-npc"]),
    dict(slug="predator", title="Predator", whose="Yours", systems=["people", "fight"],
         definition="Hostile wild NPC (wolf, and sometimes mammoth). Not herdable. Fights or hunts.",
         fight="Mammoth is also listed as hunt prey (meat) in the early-game vision and the Area of Hunt notes. The docs have not picked one role.",
         related=["herdable", "wild-role-prey", "area-of-hunt", "meat"]),
    dict(slug="bloodline", title="Bloodline", whose="Yours", systems=["people", "genetics"],
         definition="Your lineage for one run. You pick one founder species, then each generation mixes. Wipe is permadeath for that line.",
         related=["species", "hybridization", "sandbox-domination"]),
    dict(slug="part-of-the-clan", title="Part of the clan", whose="Yours", systems=["people"],
         definition="Women and herd animals claimed by the clan. They are clan members for ownership. They are still not clansmen.",
         not_="Not a clansman.",
         related=["claimed", "clansman", "woman"]),
    dict(slug="claimed", title="Claimed", whose="Yours", systems=["people"],
         definition="A herdable tied to a clan. Opposite of wild.",
         related=["wild", "herdable", "part-of-the-clan"]),
    # Exile
    dict(slug="wilderness", title="Wilderness", whose="Yours", systems=["exile", "land"],
         definition="Land no claim covers.",
         not_="Not the same as wild. Wild describes an NPC. Wilderness describes land.",
         related=["wild", "land-claim", "searcher"]),
    dict(slug="wild-caveman", title="Wild caveman", whose="Yours", systems=["exile", "people"],
         definition="A male with no land claim: exile after the flag dies, a defector, or a founder waiting for a slot. Planned. Not the same as a woman or goat going wild.",
         fight="Not in the game yet. Today males can keep a dead clan name with no claim.",
         related=["caveman", "exile", "defector", "founder"]),
    dict(slug="exile", title="Exile", whose="Yours", systems=["exile"],
         definition="The wild-caveman phase right after home is lost: no claim, no follow, no clan brain home. Planned.",
         related=["wild-caveman", "territory-wipe", "clan-brain"]),
    dict(slug="founder-candidate", title="Founder candidate", whose="Yours", systems=["exile"],
         definition="A wild caveman who passed the clan-slot check and may get a new claim. Planned.",
         related=["founder", "clan-slot", "wild-caveman"]),
    dict(slug="founder", title="Founder", whose="Yours", systems=["exile"],
         definition="That male placed with a new land claim. Clan name is his personal name. Planned.",
         related=["founder-candidate", "land-claim", "bloodline"]),
    dict(slug="clan-slot", title="Clan slot", whose="Yours", systems=["exile"],
         definition="“May the world add one more AI clan?” A budget, separate from the minimum number of clans. Planned.",
         related=["founder-candidate", "chunk-exhausted"]),
    dict(slug="defector", title="Defector", whose="Yours", systems=["exile"],
         definition="A clansman who leaves on purpose (hunger, morale) and becomes a wild caveman. Same founder path later. Planned.",
         related=["wild-caveman", "clansman", "exile"]),
    # Orders
    dict(slug="herd", title="Herd", whose="Yours", systems=["orders"],
         definition="Leading herdables (women, sheep, goats). They can be stolen, or join the clan when brought inside the claim. Not used for cavemen.",
         not_="Not Follow. Follow is the order for clansmen.",
         related=["follow", "herdable", "herder", "herd-steal"]),
    dict(slug="follow", title="Follow", whose="Yours", systems=["orders"],
         definition="Order for clansmen: stay with you or a leader, in formation, for travel and combat. You break it. It is not stolen like a herd.",
         not_="Not Herd.",
         fight="Older notes treated Follow as the clansman’s state. The current dictionary says Follow is a stance. The squad itself is a party.",
         related=["party", "stance", "herd", "break"]),
    dict(slug="party", title="Party", whose="Yours", systems=["orders"],
         definition="Clansmen in ordered follow, with stances Follow, Guard, and Attack. Agreed next names are Walk, Hunt, and Fight.",
         fight="The party name was added when Follow was narrowed to a stance.",
         related=["follow", "ordered-follow", "stance", "walk", "hunt", "fight"]),
    dict(slug="guard", title="Guard", whose="Yours", systems=["orders"],
         definition="Moving bodyguard stance: ring around the leader, tighter, more ready to fight.",
         not_="Not Defender. A defender stays on the claim border.",
         related=["defender", "stance", "follow", "attack"]),
    dict(slug="attack", title="Attack", whose="Yours", systems=["orders"],
         definition="Party stance: push to fight. The agreed next label is Fight. Raid is Fight while you are away from home, not a fourth mode.",
         related=["fight", "stance", "raid", "guard"]),
    dict(slug="stance", title="Stance", whose="Yours", systems=["orders"],
         definition="Follow, Guard, or Attack. Changes how eager they are to fight and how they stand around you.",
         related=["follow", "guard", "attack", "walk", "hunt", "fight"]),
    dict(slug="break", title="Break", whose="Yours", systems=["orders"],
         definition="B. Dismiss ordered follow. They walk home.",
         fight="Agreed next, not shipped: also split the party pile into pockets, then drop it at your claim.",
         related=["ordered-follow", "party-pile", "war-horn", "returning-from-break"]),
    dict(slug="war-horn", title="War Horn", whose="Yours", systems=["orders"],
         definition="H. Rally clansmen to you.",
         fight="Today in the docs: about 1500 px, and H during a hunt aborts the hunt. Agreed next: about 400 px, fighters only, and a searcher who is already herding ignores the horn.",
         related=["break", "party", "searcher", "raid"]),
    dict(slug="direct-control", title="Direct control", whose="Yours", systems=["orders"],
         definition="You steer only your own body. Clansmen are AI plus these orders.",
         related=["primitive-command-model", "clansman"]),
    dict(slug="primitive-command-model", title="Primitive command model", whose="Yours", systems=["orders"],
         definition="Lore limit: gesture-level orders only (follow, guard, attack, defend the claim, horn, break). No modern tactic menu.",
         related=["follow", "guard", "attack", "war-horn", "break"]),
    dict(slug="walk", title="Walk", whose="Yours", systems=["orders"],
         definition="Agreed next label for the Follow stance: travel and escort, behind you. Not shipped.",
         related=["follow", "stance", "party-dock", "hunt", "fight"]),
    dict(slug="hunt", title="Hunt", whose="Yours", systems=["orders"],
         definition="Agreed next party label for prey. Not the same as the AI hunt intent. Not shipped. Today, H during a hunt aborts the hunt.",
         not_="Not hunt intent. Hunt here is a party label you would press. Hunt intent is the clan planner’s flag.",
         related=["walk", "fight", "hunt-intent", "war-horn"]),
    dict(slug="fight", title="Fight", whose="Yours", systems=["orders"],
         definition="Agreed next label for the Attack stance. Raid is Fight while you are away from home, not a fourth mode. Not shipped.",
         related=["attack", "raid", "walk", "party-dock"]),
    dict(slug="party-dock", title="Party dock", whose="Yours", systems=["orders"],
         definition="Agreed next, not shipped: one window for the band. A thin bar, or a bigger sheet when you press I.",
         related=["party-pile", "party", "walk"]),
    dict(slug="party-pile", title="Party pile", whose="Yours", systems=["orders"],
         definition="Agreed next, not shipped: shared kit and loot for the band.",
         related=["party-dock", "break", "stockpile"]),
    # Land
    dict(slug="land-claim", title="Land claim", whose="Yours", systems=["land"],
         definition="The territory: the ground inside the circle, plus the object that anchors it.",
         related=["campfire", "flag", "wilderness", "territory-wipe"]),
    dict(slug="campfire", title="Campfire", whose="Yours", systems=["land"],
         definition="Tier 1. Small movable land claim. Nomad home. Radius 250 px. Up to 3 Living Huts. You can abandon camp and move without disbanding.",
         fight="An old snapshot said the campfire has no clan brain and 6 storage slots. The Sep 2026 nomad doc says it does have a clan brain (nomadic mode) and 20 slots.",
         related=["flag", "tier-1-tier-2", "nomad-mode", "clan-brain", "living-hut"]),
    dict(slug="flag", title="Flag", whose="Yours", systems=["land"],
         definition="Tier 2. Settled land claim. Radius 400 px. Full production. Destroying an enemy flag wipes that territory (loot first). Herdables go wild.",
         related=["campfire", "territory-wipe", "area-of-hunt", "tier-1-tier-2"]),
    dict(slug="tier-1-tier-2", title="Tier 1 / Tier 2", whose="Yours", systems=["land"],
         definition="Locked names. Tier 1 is the campfire. Tier 2 is the flag. Same kind of claim, different size and rules.",
         related=["campfire", "flag", "land-claim"]),
    dict(slug="village", title="Village", whose="Yours", systems=["land", "planner"],
         definition="A land claim grown large: big radius, many huts. The clan brain tracks what the clan needs and assigns work.",
         related=["land-claim", "clan-brain", "supply-demand"]),
    dict(slug="nomad-mode", title="Nomad Mode", whose="Yours", systems=["land"],
         definition="Moving the clan (player abandon-camp, or AI when resources are low).",
         not_="Not migration. Migration is only for wild animals moving on corridors.",
         related=["migration", "campfire", "clan-brain"]),
    dict(slug="migration", title="Migration", whose="Yours", systems=["land"],
         definition="Wild animals moving on corridors. Do not use this word for clans.",
         not_="Not Nomad Mode.",
         related=["nomad-mode", "predator"]),
    dict(slug="territory-wipe", title="Territory wipe", whose="Yours", systems=["land", "fight"],
         definition="Flag destroyed: inventories and buildings gone. Women and animals scatter wild. Babies despawn with the claim. Male survivors as wild cavemen are planned.",
         related=["flag", "wipe-burn-flag", "wild-caveman", "wild"]),
    # World
    dict(slug="resource-node", title="Resource node", whose="Yours", systems=["world"],
         definition="A map resource that runs out and comes back (berries, stone, tree).",
         related=["gatherable", "infinite-respawn", "resource-index"]),
    dict(slug="gatherable", title="Gatherable", whose="Yours", systems=["world"],
         definition="Something you or an NPC pick up from the map.",
         related=["resource-node", "forage", "gather-job"]),
    dict(slug="wild-wheat", title="Wild wheat", whose="Yours", systems=["world"],
         definition="Wheat that grows only outside any claim. A reason to leave home, and a reason to settle so you can farm later.",
         related=["wilderness", "grain-bread", "field"]),
    dict(slug="relic", title="Relic", whose="Yours", systems=["world", "huts"],
         definition="Rare item that does not respawn. Put it in a Shrine for a clan-wide buff. Higher flag upgrades may require relics.",
         related=["shrine", "infinite-respawn", "grave-mound"]),
    dict(slug="infinite-respawn", title="Infinite respawn", whose="Yours", systems=["world"],
         definition="Trees, stone, berries, and animals come back forever. Relics do not.",
         related=["relic", "resource-node"]),
    dict(slug="forage", title="Forage", whose="Yours", systems=["world"],
         definition="Berries and (future) roots. Food for the walk.",
         related=["meat", "grain-bread", "gatherable"]),
    dict(slug="meat", title="Meat", whose="Yours", systems=["world", "fight"],
         definition="Food from hunts or from butchering the flock.",
         related=["forage", "grain-bread", "predator", "area-of-hunt"]),
    dict(slug="grain-bread", title="Grain / bread", whose="Yours", systems=["world", "huts"],
         definition="Wild wheat, or a settled field plus an oven on the flag. A reason to settle.",
         related=["wild-wheat", "oven", "field", "flag"]),
    # Fight
    dict(slug="aop", title="AOP", whose="Yours", systems=["fight"],
         definition="Area of Perception. How far an NPC can sense others.",
         related=["aoa", "perception-area", "agro"]),
    dict(slug="aoa", title="AOA", whose="Yours", systems=["fight"],
         definition="Area of Agro. Inner circle inside AOP. A hostile here raises agro (fight or flight).",
         related=["aop", "agro"]),
    dict(slug="agro", title="Agro", whose="Yours", systems=["fight"],
         definition="Tension from 0 to 100. Enter combat at 70. Leave combat under 60. Raised by trespass, AOA, damage, and herd steal.",
         related=["aoa", "combat", "herd-steal"]),
    dict(slug="herd-steal", title="Herd steal", whose="Yours", systems=["fight", "orders"],
         definition="Pulling another clan’s herdable. The same clan cannot steal from itself. A cross-clan pull can. Blocked while that herder’s clansmen are in ordered follow.",
         related=["herd", "claimed", "ordered-follow", "cordage"]),
    dict(slug="combat", title="Combat", whose="Yours", systems=["fight"],
         definition="Auto fight: wind up, hit, recover. A stagger can cancel the windup. Death leaves a corpse.",
         related=["agro", "corpse", "attack"]),
    dict(slug="corpse", title="Corpse", whose="Yours", systems=["fight"],
         definition="Dead body you can loot.",
         related=["combat", "grave-mound", "meat"]),
    dict(slug="raid", title="Raid", whose="Yours", systems=["fight"],
         definition="Hostile trip: take building and flag goods. Horn plus ordered followers is a war party.",
         related=["war-horn", "loot-take-goods", "territory-wipe", "fight"]),
    dict(slug="leader-succession", title="Leader succession", whose="Yours", systems=["fight"],
         definition="When a leader dies, the oldest clansman (or a similar rule) continues the AI clan.",
         related=["clansman", "combat"]),
    dict(slug="cordage", title="Cordage", whose="Yours", systems=["fight"],
         definition="Item you use on an enemy’s claimed herdable to bond and lead them out. Without it, a peace walk cannot take claimed herdables. Mostly planned.",
         related=["steal-take-herd", "claimed", "herd"]),
    dict(slug="steal-take-herd", title="STEAL / TAKE HERD", whose="Yours", systems=["fight"],
         definition="Take their flock with cordage. Not the same as fighting the flock. Mostly planned.",
         not_="Not combat against the animals.",
         related=["cordage", "herd-steal", "loot-take-goods"]),
    dict(slug="loot-take-goods", title="LOOT / TAKE GOODS", whose="Yours", systems=["fight"],
         definition="Empty building and flag inventories. Mostly planned.",
         related=["raid", "steal-take-herd", "wipe-burn-flag"]),
    dict(slug="kill-attack-men", title="KILL / ATTACK MEN", whose="Yours", systems=["fight"],
         definition="Fight their clansmen. Mostly planned.",
         related=["combat", "clansman", "raid"]),
    dict(slug="wipe-burn-flag", title="WIPE / BURN FLAG", whose="Yours", systems=["fight"],
         definition="Destroy the flag after loot rules. Mostly planned.",
         related=["territory-wipe", "flag", "loot-take-goods"]),
    # Planner (your words)
    dict(slug="clan-brain", title="ClanBrain", whose="Yours", systems=["planner"],
         definition="The clan’s planner, owned by the territory (flag or campfire). It sets how many defenders and searchers, and whether to raid or hunt. People pull those orders. They are not micromanaged one by one.",
         related=["defender-quota", "searcher-quota", "strategic-state", "campfire", "flag"]),
    dict(slug="defender-quota", title="Defender quota", whose="Yours", systems=["planner"],
         definition="How many clansmen the brain wants on the border.",
         related=["defender", "clan-brain", "searcher-quota"]),
    dict(slug="searcher-quota", title="Searcher quota", whose="Yours", systems=["planner"],
         definition="How many clansmen the brain wants out looking for herdables.",
         related=["searcher", "clan-brain", "herd"]),
    dict(slug="supply-demand", title="Supply / demand", whose="Yours", systems=["planner"],
         definition="The brain tracks food, resources, and buildings, then assigns work.",
         related=["clan-brain", "village", "economic-weights"]),
    dict(slug="strategic-state", title="Strategic state", whose="Yours", systems=["planner"],
         definition="Mood that gates those plans: peaceful, defensive, aggressive, raiding, recovering.",
         related=["clan-brain", "raid"]),
    # Buildings
    dict(slug="living-hut", title="Living Hut", whose="Yours", systems=["huts"],
         definition="One woman and her children. Pregnancy needs this hut and the woman inside the claim.",
         fight="gdd.md still says the hut has 0 women and only raises the baby pool. bible.md says 1 woman and pregnancy.",
         related=["woman", "baby", "baby-pool", "campfire"]),
    dict(slug="supply-hut", title="Supply Hut", whose="Yours", systems=["huts"],
         definition="Extra shared storage.",
         fight="Storage Hut is the other name for the same job.",
         related=["storage-hut", "stockpile"]),
    dict(slug="storage-hut", title="Storage Hut", whose="Yours", systems=["huts"],
         definition="Extra shared storage. Same job as Supply Hut.",
         fight="Two names, one job.",
         related=["supply-hut", "stockpile"]),
    dict(slug="shrine", title="Shrine", whose="Yours", systems=["huts"],
         definition="Holds relics. Buffs the whole clan.",
         related=["relic", "grave-mound"]),
    dict(slug="farm", title="Farm", whose="Yours", systems=["huts"],
         definition="Wool from sheep, milk from goats. Needs a woman.",
         related=["dairy", "woman", "herdable"]),
    dict(slug="dairy", title="Dairy", whose="Yours", systems=["huts"],
         definition="Cheese and butter from milk. Needs a woman.",
         fight="Dairy Farm is the other name in the building list.",
         related=["dairy-farm", "farm", "woman"]),
    dict(slug="dairy-farm", title="Dairy Farm", whose="Yours", systems=["huts"],
         definition="Cheese and butter from milk. Needs a woman. Same job as Dairy.",
         related=["dairy", "farm"]),
    dict(slug="oven", title="Oven", whose="Yours", systems=["huts"],
         definition="Wood plus grain becomes bread. Timed.",
         fight="gdd.md still says Bakery: wheat plus any edible becomes flavored bread.",
         related=["bakery", "grain-bread"]),
    dict(slug="bakery", title="Bakery", whose="Yours", systems=["huts"],
         definition="GDD name: wheat plus any edible becomes flavored bread. The current short list says Oven instead.",
         related=["oven", "grain-bread"]),
    dict(slug="field", title="Field", whose="Yours", systems=["huts"],
         definition="Proto-farm crop ring. Planned. Flag only. The campfire does not get it.",
         related=["flag", "campfire", "grain-bread", "wild-wheat"]),
    dict(slug="medic-hut", title="Medic Hut", whose="Yours", systems=["huts"],
         definition="Planned. Hurt people walk here if berries are stocked.",
         related=["forage", "combat"]),
    dict(slug="grave-mound", title="Grave Mound", whose="Yours", systems=["huts"],
         definition="From the edits idea list: only the player can be buried, age Good or better, one relic slot, raiders can smash it.",
         related=["corpse", "relic", "quality-tier", "shrine"]),
    dict(slug="spinner", title="Spinner", whose="Yours", systems=["huts"],
         definition="GDD building still named, not on the current short list. Cloth from wool. Needs a woman.",
         related=["farm", "tailor"]),
    dict(slug="armory", title="Armory", whose="Yours", systems=["huts"],
         definition="GDD building still named, not on the current short list. Weapons. Needs a woman.",
         related=["tailor"]),
    dict(slug="tailor", title="Tailor", whose="Yours", systems=["huts"],
         definition="GDD building still named, not on the current short list. Armor, backpacks, travois. Needs a woman.",
         related=["armory", "spinner"]),
    # Genetics
    dict(slug="species", title="Species", whose="Yours", systems=["genetics"],
         definition="One hominid line. Sets the trait pool.",
         fight="hominids.md lists Sapiens, Neanderthal, Heidelbergensis, Denisovan, and Floresiensis. earlygame.md instead lists Erectus and different bonuses.",
         related=["trait", "hybridization", "bloodline"]),
    dict(slug="trait", title="Trait", whose="Yours", systems=["genetics"],
         definition="Inheritable bonus (example: more strength). Up to 6 per NPC. Each trait passes from mother or father about half the time. Only traits that parent’s species can have.",
         related=["gene", "species", "stats"]),
    dict(slug="gene", title="Gene", whose="Yours", systems=["genetics"],
         definition="Optional dominant or recessive layer on a trait. A finer model in the reproduction notes.",
         related=["trait", "hybridization"]),
    dict(slug="hybridization", title="Hybridization", whose="Yours", systems=["genetics"],
         definition="Child species comes from the parents (about half the time which parent). Traits can mix across those pools.",
         related=["species", "trait", "bloodline"]),
    dict(slug="stats", title="Stats", whose="Yours", systems=["genetics"],
         definition="Numbers such as strength and intelligence. Often the average of the parents, plus a small change.",
         related=["trait", "quality-tier"]),
    dict(slug="quality-tier", title="Quality tier", whose="Yours", systems=["genetics"],
         definition="From the edits idea list: age bands for males — Flawed, Common, Good, Fine, Master, Legendary — with a stat percent and a border color.",
         related=["stats", "grave-mound"]),
    dict(slug="genome", title="Genome", whose="Yours", systems=["genetics"],
         definition="Old term: a big list of body-shape numbers. The child is the average of the parents plus a mutation.",
         fight="Current docs say looks are sprite sheets, not that morph genome. The draft says do not treat Genome as live. Status stays Draft until you confirm it is retired.",
         not_="Not Appearance (2D).",
         related=["appearance-2d", "dragonbones"]),
    dict(slug="sandbox-domination", title="Sandbox / domination", whose="Yours", systems=["people"],
         definition="No win screen. The goal is your bloodline dominating the map, with brutal raids and permadeath.",
         related=["bloodline", "raid", "territory-wipe"]),
    # Sim names
    dict(slug="ordered-follow", title="Ordered follow", whose="Sim name", systems=["sim", "orders"],
         definition="Clansmen locked into a party command. Not broken by a normal herd steal. Cleared by Break or the leash.",
         related=["follow", "party", "break", "follow-is-ordered"],
         source="game_dictionary.md"),
    dict(slug="follow-is-ordered", title="follow_is_ordered", whose="Sim name", systems=["sim", "orders"],
         definition="On or off flag while ordered follow is active (drag, menu, horn, or an AI raid party). Blocks cross-clan herd steal.",
         related=["ordered-follow", "herd-steal", "command-context"],
         source="bible.md terminology"),
    dict(slug="command-context", title="command_context", whose="Sim name", systems=["sim", "orders"],
         definition="The packet on those clansmen: mode (follow, guard, or attack), tuning, who commands them, and when it was issued.",
         related=["stance", "ordered-follow", "formation-slots"],
         source="game_dictionary.md"),
    dict(slug="formation-slots", title="formation_slots", whose="Sim name", systems=["sim", "orders"],
         definition="Saved stand-points around the leader (you or an NPC) so followers steer to a slot.",
         related=["party", "command-context"],
         source="game_dictionary.md"),
    dict(slug="rts-config", title="RTS_CONFIG", whose="Sim name", systems=["sim", "orders"],
         definition="The settings sheet for rally radius, horn cooldown, leash, catch-up speed, and stance numbers.",
         related=["war-horn", "stance"],
         source="game_dictionary.md"),
    dict(slug="returning-from-break", title="returning_from_break", whose="Sim name", systems=["sim", "orders"],
         definition="Priority bump so clansmen walk home after Break instead of wandering off.",
         related=["break"],
         source="game_dictionary.md"),
    dict(slug="perception-area", title="PerceptionArea", whose="Sim name", systems=["sim", "fight"],
         definition="The sensor circle that implements AOP. Tracks who is in range and feeds agro, combat, and herd detection.",
         related=["aop", "aoa", "herd-influence-area"],
         source="bible.md"),
    dict(slug="enemies-in-claim", title="EnemiesInClaim", whose="Sim name", systems=["sim", "fight"],
         definition="A sensor on the land claim that notices intruders for defenders.",
         related=["defender", "land-claim", "agro"],
         source="game_dictionary.md"),
    dict(slug="herd-influence-area", title="HerdInfluenceArea", whose="Sim name", systems=["sim", "orders"],
         definition="A sensor on each herdable. Overlap builds influence until they attach or a contest resolves.",
         related=["herdable", "herder", "herd"],
         source="game_dictionary.md"),
    dict(slug="fighter-activity", title="Fighter activity", whose="Sim name", systems=["sim", "fight"],
         definition="A count of who is in combat, defend, agro, or raid right now. Not how many clansmen exist.",
         not_="Not a headcount of clansmen.",
         related=["clansman", "combat", "defender"],
         source="bible.md"),
    dict(slug="area-of-hunt", title="Area of Hunt", whose="Sim name", systems=["sim", "planner", "fight"],
         definition="A ring on the flag wider than the claim. Counts prey (deer, mammoth) for the AI hunt. Herdables in that ring are still a search job, not a hunt. The campfire has no Area of Hunt.",
         related=["hunt-intent", "flag", "campfire", "predator", "searcher"],
         source="bible.md, nomad.md"),
    dict(slug="hunt-intent", title="Hunt intent", whose="Sim name", systems=["sim", "planner"],
         definition="AI clans: the brain says hunt when that ring has prey and the food math allows. Player clans: the brain does not run the hunt. You use Peace, Agro, or Hunt.",
         not_="Not the agreed-next Hunt party label.",
         related=["area-of-hunt", "hunt", "clan-brain"],
         source="bible.md"),
    dict(slug="wild-role-prey", title="WildRole.PREY", whose="Sim name", systems=["sim", "fight"],
         definition="Label for deer and mammoth: hunt targets that flee. Not herdables.",
         related=["predator", "area-of-hunt", "herdable"],
         source="bible.md"),
    dict(slug="food-days-buffer", title="food_days_buffer", whose="Sim name", systems=["sim", "planner"],
         definition="Pantry in days: stored food calories divided by what the clan eats per day. Gates work, hunt, raid, breeding, and the off-screen sim.",
         related=["calories-days-buffer", "forage", "meat", "grain-bread"],
         source="bible.md, earlygame_vision.md"),
    dict(slug="calories-days-buffer", title="calories_days_buffer", whose="Sim name", systems=["sim", "planner"],
         definition="The same number as food_days_buffer. Older name kept in sync.",
         related=["food-days-buffer"],
         source="bible.md"),
    dict(slug="job-pressure", title="Defend / search / gather pressure", whose="Sim name", systems=["sim", "planner"],
         definition="Three weights from 0 to 1, forced to sum cleanly, that bias quotas and job urgency, beside the older economic weights.",
         related=["economic-weights", "defender-quota", "searcher-quota"],
         source="bible.md"),
    dict(slug="economic-weights", title="Economic weights", whose="Sim name", systems=["sim", "planner"],
         definition="food_weight, resource_weight, build_weight, and herd_weight. They bias which jobs people pick.",
         related=["supply-demand", "job-pressure"],
         source="game_dictionary.md"),
    dict(slug="survival-mode", title="Survival mode", whose="Sim name", systems=["sim", "planner"],
         definition="An AI clan with fewer than 2 fighters skips hunt and raid. Gather and herd only.",
         related=["hunt-intent", "raid", "clan-brain"],
         source="bible.md"),
    dict(slug="task", title="Task", whose="Sim name", systems=["sim", "planner"],
         definition="One step: move, gather, or drop.",
         related=["job", "gather-job"],
         source="game_dictionary.md"),
    dict(slug="job", title="Job", whose="Sim name", systems=["sim", "planner"],
         definition="An ordered list of tasks.",
         related=["task", "gather-job", "occupation"],
         source="game_dictionary.md"),
    dict(slug="gather-job", title="Gather job", whose="Sim name", systems=["sim", "planner"],
         definition="Move to a resource, gather, move back to the claim, auto-deposit near the center.",
         related=["job", "gatherable", "deposit-threshold"],
         source="game_dictionary.md"),
    dict(slug="deposit-threshold", title="Deposit threshold", whose="Sim name", systems=["sim", "planner"],
         definition="About 40 percent of slots full (at least 3) means go deposit. Keep one food stack. Send the rest to the claim.",
         related=["gather-job", "stockpile"],
         source="game_dictionary.md"),
    dict(slug="occupation", title="Occupation", whose="Sim name", systems=["sim", "huts"],
         definition="A building slot assignment (woman to a hut, animal to a farm): request the slot, then confirm arrival.",
         related=["living-hut", "farm", "woman"],
         source="game_dictionary.md"),
    dict(slug="simulation-manager", title="SimulationManager", whose="Sim name", systems=["sim", "planner"],
         definition="The clock that ticks on a fixed step (docs say about 120 seconds) for personal calories and farm or dairy pools.",
         related=["food-days-buffer", "farm", "dairy"],
         source="bible.md"),
    dict(slug="resource-index", title="ResourceIndex", whose="Sim name", systems=["sim", "world"],
         definition="A grid (about 200 px cells) so a claim can ask what resources are near it.",
         related=["resource-node", "land-claim"],
         source="game_dictionary.md"),
    dict(slug="hostile-entity-index", title="HostileEntityIndex", whose="Sim name", systems=["sim", "fight"],
         definition="Fast lookup for hostile NPCs.",
         related=["predator", "enemies-in-claim"],
         source="game_dictionary.md"),
    dict(slug="claim-building-index", title="ClaimBuildingIndex", whose="Sim name", systems=["sim", "huts"],
         definition="Which buildings sit inside which claim.",
         related=["land-claim", "living-hut"],
         source="game_dictionary.md"),
    dict(slug="pseudo-biome", title="pseudo-biome", whose="Sim name", systems=["sim", "world"],
         definition="A code-only label per chunk (forest, plains, rocky, swamp) used for off-screen gathering math. Not the biomes the player sees. Those are not shipped under this name.",
         related=["wilderness", "resource-node"],
         source="bible.md"),
    dict(slug="mutation-store", title="MutationStore", whose="Sim name", systems=["sim", "land"],
         definition="Where the world remembers what players changed after the seed (chopped, built, claimed, clan deaths).",
         related=["chunk-exhausted", "land-claim"],
         source="clan_founding_and_exile.md, earlygame.md"),
    dict(slug="chunk-exhausted", title="Chunk exhausted", whose="Sim name", systems=["sim", "exile"],
         definition="A chunk has recorded enough clan deaths (default 3) that seeded clans stop there. Founder clans are a separate question.",
         related=["clan-slot", "mutation-store", "founder"],
         source="clan_founding_and_exile.md"),
    dict(slug="appearance-2d", title="Appearance (2D)", whose="Sim name", systems=["sim", "genetics"],
         definition="How an NPC looks: sprite sheets. Not a morph body, and not Mixamo.",
         not_="Not Genome.",
         related=["genome", "dragonbones"],
         source="game_dictionary.md"),
    dict(slug="dragonbones", title="DragonBones", whose="Sim name", systems=["sim", "genetics"],
         definition="Not used. Removed. 2D is sprite sheets only.",
         related=["appearance-2d", "genome"],
         source="bible.md"),
    dict(slug="stockpile", title="Stockpile", whose="Sim name", systems=["sim", "huts"],
         definition="Claim, building, or campfire list: one row per item type, stacked. Empty rows hidden except one drop row.",
         related=["supply-hut", "hotbar", "deposit-threshold"],
         source="game_dictionary.md"),
    dict(slug="hotbar", title="Hotbar", whose="Sim name", systems=["sim"],
         definition="Keys 1 through 8 are gear. Keys 9 and 0 are food you eat on the key.",
         related=["stockpile"],
         source="game_dictionary.md"),
]


SYSTEM_PAGES = [
    ("people", "People", "Who is in the clan, and who is not.", ["people"]),
    ("herd-and-follow", "Herd and follow", "How you move other people. Herd is for herdables. Follow is for clansmen.", ["orders"]),
    ("land", "Land", "Campfire, flag, and the ground inside a claim.", ["land", "world"]),
    ("fight-and-raid", "Fight and raid", "Sensing, agro, combat, and the raid verbs.", ["fight"]),
    ("huts-and-babies", "Huts and babies", "Housing, storage, and food buildings.", ["huts"]),
    ("genetics", "Genetics", "Species, traits, and how a child is mixed.", ["genetics"]),
    ("clan-planner", "Clan planner", "The clan brain and the quotas it sets.", ["planner"]),
    ("sim-names", "Sim names", "Names from the write-ups. Each one should point at the player word it serves.", ["sim"]),
    ("exile", "Exile", "Planned path when a male loses his claim. Not current play.", ["exile"]),
]


def search_keywords(t: dict) -> str:
    title = t["title"]
    parts = [title.lower(), t["slug"].replace("-", " ")]
    glued = "".join(c for c in title if c.isalnum()).lower()
    if glued and glued not in parts:
        parts.append(glued)
    return " ".join(dict.fromkeys(parts))


def render_term(t: dict) -> str:
    lines = [
        "---",
        "search:",
        f"  keywords: {search_keywords(t)}",
        "---",
        "",
        f"# {t['title']}",
        "",
        "**Status:** Draft",
        "",
        f"**Whose word:** {t['whose']}",
        "",
        "## Definition",
        "",
        t["definition"],
        "",
    ]
    if t.get("not_"):
        lines += ["## What it is not", "", t["not_"], ""]
    if t.get("fight"):
        lines += ["## Doc fight", "", t["fight"], ""]
    if t.get("source"):
        lines += ["## Where the docs say this", "", t["source"], ""]
    lines += ["## Related", ""]
    by_slug = {x["slug"]: x for x in TERMS_DATA}
    for slug in t.get("related", []):
        other = by_slug[slug]
        lines.append(f"- [{other['title']}]({slug}.md)")
    system_for = []
    tags = set(t["systems"])
    for slug, title, _blurb, keys in SYSTEM_PAGES:
        if tags.intersection(keys):
            system_for.append((slug, title))
    if system_for:
        lines.append("")
        lines.append("## Systems")
        lines.append("")
        for slug, title in system_for:
            lines.append(f"- [{title}](../systems/{slug}.md)")
    lines.append("")
    return "\n".join(lines)


def render_system(slug: str, title: str, blurb: str, keys: list) -> str:
    lines = [
        f"# {title}",
        "",
        "**Status:** Draft",
        "",
        blurb,
        "",
        "This page does not add rules. It only links the words.",
        "",
    ]
    grouped = [t for t in TERMS_DATA if set(t["systems"]).intersection(keys)]
    yours = [t for t in grouped if t["whose"] == "Yours"]
    sim = [t for t in grouped if t["whose"] != "Yours"]
    if yours:
        lines += ["## Your words", ""]
        for t in yours:
            lines.append(f"- [{t['title']}](../terms/{t['slug']}.md)")
        lines.append("")
    if sim:
        lines += ["## Sim names", ""]
        for t in sim:
            lines.append(f"- [{t['title']}](../terms/{t['slug']}.md)")
        lines.append("")
    return "\n".join(lines)


# Pages edited by hand (extended sections). Seed skips these so `python tools/seed_wiki_drafts.py` does not wipe them.
HAND_MAINTAINED = frozenset({"clan-brain", "morale-bar-clan", "morale-bar-fighter"})


def main() -> None:
    TERMS.mkdir(parents=True, exist_ok=True)
    SYSTEMS.mkdir(parents=True, exist_ok=True)
    slugs = [t["slug"] for t in TERMS_DATA]
    if len(slugs) != len(set(slugs)):
        raise SystemExit("duplicate slug")
    by_slug = {t["slug"]: t for t in TERMS_DATA}
    for t in TERMS_DATA:
        for slug in t.get("related", []):
            if slug not in by_slug:
                raise SystemExit(f"missing related {slug} from {t['slug']}")
    for t in TERMS_DATA:
        if t["slug"] in HAND_MAINTAINED:
            continue
        (TERMS / f"{t['slug']}.md").write_text(render_term(t), encoding="utf-8")
    for slug, title, blurb, keys in SYSTEM_PAGES:
        (SYSTEMS / f"{slug}.md").write_text(render_system(slug, title, blurb, keys), encoding="utf-8")
    print(f"wrote {len(TERMS_DATA)} terms and {len(SYSTEM_PAGES)} systems")


if __name__ == "__main__":
    main()
